DROP TABLE IF EXISTS balances;

CREATE TABLE balances
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	crypto VARCHAR(50) NOT NULL,
  address VARCHAR(50) NOT NULL,
  amount VARCHAR(50) NOT NULL,
  amount_usd VARCHAR(50) NOT NULL,
  insertedTime VARCHAR(50) NOT NULL
);
