DROP TABLE IF EXISTS balances;

CREATE TABLE balances (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	address VARCHAR(50) NOT NULL,
	amount VARCHAR(50) NOT NULL,
	amount_usd VARCHAR(50) NOT NULL,
	timestamp VARCHAR(50) NOT NULL,
);
